export {
  // client
  FIRST_FIREBASE_API_KEY,
  FIRST_FIREBASE_AUTH_DOMAIN,
  FIRST_FIREBASE_PROJECT_ID,
  FIRST_FIREBASE_STORAGE_BUCKET,
  FIRST_FIREBASE_MESSAGING_SENDER_ID,
  FIRST_FIREBASE_APP_ID,
  FIRST_FIREBASE_MEASUREMENT_ID,

  // admin
  FIRST_FIREBASE_ADMIN_TYPE,
  FIRST_FIREBASE_ADMIN_PROJECT_ID,
  FIRST_FIREBASE_ADMIN_PRIVATE_KEY_ID,
  FIRST_FIREBASE_ADMIN_PRIVATE_KEY,
  FIRST_FIREBASE_ADMIN_CLIENT_EMAIL,
  FIRST_FIREBASE_ADMIN_CLIENT_ID,
  FIRST_FIREBASE_ADMIN_AUTH_URI,
  FIRST_FIREBASE_ADMIN_TOKEN_URI,
  FIRST_FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL,
  FIRST_FIREBASE_ADMIN_CLIENT_X509_CERT_URL,
  FIRST_FIREBASE_ADMIN_DOMAIN_URL,
}  from './firebaseFirstProject'

export {
  // client
  SECOND_FIREBASE_API_KEY,
  SECOND_FIREBASE_AUTH_DOMAIN,
  SECOND_FIREBASE_PROJECT_ID,
  SECOND_FIREBASE_STORAGE_BUCKET,
  SECOND_FIREBASE_MESSAGING_SENDER_ID,
  SECOND_FIREBASE_APP_ID,
  SECOND_FIREBASE_MEASUREMENT_ID,

  // admin
  SECOND_FIREBASE_ADMIN_TYPE,
  SECOND_FIREBASE_ADMIN_PROJECT_ID,
  SECOND_FIREBASE_ADMIN_PRIVATE_KEY_ID,
  SECOND_FIREBASE_ADMIN_PRIVATE_KEY,
  SECOND_FIREBASE_ADMIN_CLIENT_EMAIL,
  SECOND_FIREBASE_ADMIN_CLIENT_ID,
  SECOND_FIREBASE_ADMIN_AUTH_URI,
  SECOND_FIREBASE_ADMIN_TOKEN_URI,
  SECOND_FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL,
  SECOND_FIREBASE_ADMIN_CLIENT_X509_CERT_URL,
  SECOND_FIREBASE_ADMIN_DOMAIN_URL,
} from './firebaseSecondProject'

export {
  // client
  THIRD_FIREBASE_API_KEY,
  THIRD_FIREBASE_AUTH_DOMAIN,
  THIRD_FIREBASE_PROJECT_ID,
  THIRD_FIREBASE_STORAGE_BUCKET,
  THIRD_FIREBASE_MESSAGING_SENDER_ID,
  THIRD_FIREBASE_APP_ID,
  THIRD_FIREBASE_MEASUREMENT_ID,

  // admin
  THIRD_FIREBASE_ADMIN_TYPE,
  THIRD_FIREBASE_ADMIN_PROJECT_ID,
  THIRD_FIREBASE_ADMIN_PRIVATE_KEY_ID,
  THIRD_FIREBASE_ADMIN_PRIVATE_KEY,
  THIRD_FIREBASE_ADMIN_CLIENT_EMAIL,
  THIRD_FIREBASE_ADMIN_CLIENT_ID,
  THIRD_FIREBASE_ADMIN_AUTH_URI,
  THIRD_FIREBASE_ADMIN_TOKEN_URI,
  THIRD_FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL,
  THIRD_FIREBASE_ADMIN_CLIENT_X509_CERT_URL,
  THIRD_FIREBASE_ADMIN_DOMAIN_URL,
} from './firebaseThirdProject'

